### PR TITLE
add ubuntu script

### PR DESCRIPTION
**Pull request by mrunderline**
resolving issue #1

### CODE REVIEW

**Review by OrBin — CHANGES_REQUESTED** [review]
Thanks!
The value for `"image"` should be the name of the docker image. In this case, I believe it should be `"ubuntu:19.04"`.
Can you please fix it?

**Comment by mrunderline** [comment]
It's done, thanks for your attention and help!

**Comment by OrBin** [comment]
> It's done, thanks for your attention and help!

Thanks. Have you tested it? I tried to run it now and it doesn't seem to work - the packages directory has no downloaded package.
Also, please change `apt` to `apt-get`, since `apt` declares that it does not yet have a stable CLI.

**Comment by mrunderline** [comment]
I think it's almost done; I've tested it and it worked successfully!

**Comment by OrBin** [comment]
Thanks!
Now a little more (I hope it's the latest): a `-y` flag is required after `install` in the script.
Also, the packages directory contains `lock` file and `partial/` directory, can you please add a line to remove them?

**Comment by mrunderline** [comment]
it's done @OrBin! please feel free to comment or ask for any changes.

**Review by OrBin — APPROVED** [review]
Great, thanks!

**Comment by OrBin** [comment]
This closes #1.

**Pull request merged**
